introduced environment variable

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -46,6 +46,8 @@ jobs:
           docker run -d \
             --name fms-auth-test \
             -p 8000:8000 \
+            -e MONGODB_URL="${{ secrets.DATABASE_URL }}" \
+            -e DATABASE_NAME = "${{ secrets.DATABASE_NAME }}" \
             fms-auth:${{ github.sha }}
 
       - name: Check container
@@ -53,6 +55,10 @@ jobs:
           sleep 5
           docker ps
           docker logs fms-auth-test
+          if [ "$(docker inspect -f '{{.State.Running}}' fms-auth-test)" != "true" ]; then
+            echo "Container failed to start"
+            exit 1
+          fi
 
       
 
